blank_issues_enabled: true
contact_links:
  - name: ðŸ’¬ Code& Slack
    url: https://teamcodeand.slack.com/
    about: "For anything urgent (site down, checkout not accepting payments, etc), ask us in Slack."
